name: Unit Tests # name of the test

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm test ./__tests__/pseudo.tests.js # the actual testing line

  docs:
    name: Build & Publish Site + API Docs
    runs-on: ubuntu-latest
    needs: tests
    steps:
      # 1) grab your repo
      - uses: actions/checkout@v4

      # 2) ensure Node (and your deps) are installed
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci

      # 3) generate your JSDoc into docs/docs
      - name: Generate API docs
        run: npx jsdoc -c jsdoc.json -r -d docs/docs website/js

      # 4) copy the static site into docs root
      - name: Copy sample site
        run: cp -R website/* docs/

      # 5) push the entire docs/ folder to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
