name: Unit tests, end-to-end tests, and coverage

on: [push, pull_request]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:unit   # assumes the "test" script runs Jest with --coverage

      - name: Install Codacy coverage reporter
        run: npm install --no-save codacy-coverage

      - name: Send coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          npx codacy-coverage < coverage/lcov.info

      - name: Run end-to-end tests
        run: npm run test:e2e
